name: Build, Deploy, and Release

on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'

jobs:
  build-deploy-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Build Web Version
      run: flutter build web --release --dart-define=APP_ENV=prod
    - name: Accept Android SDK licenses
      run: echo yes | sdkmanager --licenses

    - name: Build APK
      run: |
        flutter build apk --release --dart-define=APP_ENV=prod
        mv build/app/outputs/apk/release/app-release.apk build/app-release-${{ github.ref_name }}.apk

    - name: Zip Web Build
      run: zip -r web-build-${{ github.ref_name }}.zip build/web

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.6'

    - name: Deploy to Firebase
      run: julia deployfirebase.jl
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/app-release-${{ github.ref_name }}.apk
          web-build-${{ github.ref_name }}.zip
        body: |
          Automatic build for version ${{ github.ref_name }}
          - Web version deployed to Firebase
          - APK attached for mobile installation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}